fix(outposts): fix bff secrets

diff --git a/.github/workflows/conductor-auto-migrator.yml b/.github/workflows/conductor-auto-migrator.yml
--- a/.github/workflows/conductor-auto-migrator.yml
+++ b/.github/workflows/conductor-auto-migrator.yml
@@ -38,18 +38,16 @@ jobs:
       - name: Print Conductor URL
         run: echo "Conductor URL for environment -> $CONDUCTOR_URL"
 
-      - name: Remove existing Docker image
+
+      - name: Check if Docker container exists
         run: |
-            docker --version
-            docker ps
-            docker ps -a
-            CONTAINER=""
-            
-            if [[ ! -z "$CONTAINER" ]]; then
-                echo "build_required=false" >> $GITHUB_ENV
-              else
-                echo "build_required=true" >> $GITHUB_ENV
-            fi
+          CONTAINER=$(docker ps -a | grep "conductor-workflow-migrator-container" || true) 
+
+          if [[ ! -z "$CONTAINER" ]]; then
+              echo "build_required=false" >> $GITHUB_ENV
+          else
+              echo "build_required=true" >> $GITHUB_ENV
+          fi
         continue-on-error: true
 
       - name: Adjust the config based on selected environment
@@ -71,4 +69,5 @@ jobs:
       - name: Run the migrator
         run: |
           cd ./platform/conductor/${{ inputs.environment }}
+          docker rm -f workflow-migrator-container
           docker run --name workflow-migrator-container -v "$PWD/config:/etc/config/workflow-migrator" conductor-workflow-migrator deploy
