feat(cronjobs): add cronjobs workflow for lms

diff --git a/.github/workflows/cronjob.yml b/.github/workflows/cronjob.yml
--- a/.github/workflows/cronjob.yml
+++ b/.github/workflows/cronjob.yml
@@ -90,14 +90,16 @@ jobs:
           echo "Schedule provided: ${{ inputs.schedule }}"
 
           # Updated regular expression to match the Cron format (minute, hour, day of month, month, day of week)
-          regex="^([0-5]?[0-9]) ([01]?[0-9]|2[0-3]) ([01]?[0-9]|[12][0-9]|3[01]) (1[0-2]|0?[1-9]) ([0-6,]+|\*)$"
+          cron_pattern="^(\*|([0-5]?[0-9])) (\*|([01]?[0-9]|2[0-3])) (\*|([12]?[0-9]|3[01])) (\*|([1-9]|1[0-2])) (\*|([0-6](?:,[0-6])*(?:,[0-6])*)|([0-6]))$"
+
+          echo "${{ inputs.schedule }}" | grep -Pq "$cron_pattern"
 
           # Check if the schedule matches the regex
-          if [[ "10 2 * * 0,3" =~ $regex ]]; then
-              echo "CronJob schedule is valid."
+          if [ $? -eq 0 ]; then
+              echo "The cron expression '$cron_expression' is valid."
           else
-              echo "Invalid CronJob schedule format. Please use a valid cron format."
-              exit 1
+              echo "The cron expression '$cron_expression' is invalid."
+              exit 1  # Exit with error if the cron expression is invalid
           fi
 
       - name: Apply CronJob Schedule Change
