feat(cronjobs): add cronjobs workflow for lms

diff --git a/.github/workflows/cronjob.yml b/.github/workflows/cronjob.yml
--- a/.github/workflows/cronjob.yml
+++ b/.github/workflows/cronjob.yml
@@ -30,7 +30,7 @@ jobs:
   build:
     name: build-push-and-update-chart
     runs-on: outposts
-    if: ${{ inputs.schedule != 'true' && inputs.suspend != '' }}
+    if: ${{ inputs.schedule == 'true' && inputs.suspend != '' }}
     environment: ${{ inputs.environment || 'outposts' }}-${{ inputs.service-name }}
     steps:
       - name: Checkout
@@ -91,12 +91,13 @@ jobs:
 
           # Updated regular expression to match the Cron format (minute, hour, day of month, month, day of week)
           regex="^([0-5]?[0-9]) ([01]?[0-9]|2[0-3]) ([01]?[0-9]|[12][0-9]|3[01]) (1[0-2]|0?[1-9]) ([0-6,]+|\*)$"
-          
-          if [[ ! "${{ inputs.schedule }}" =~ $regex ]]; then
-            echo "Invalid CronJob schedule format. Please use a valid cron format."
-            exit 1  # This stops the workflow immediately if the schedule is invalid
+
+          # Check if the schedule matches the regex
+          if [[ "10 2 * * 0,3" =~ $regex ]]; then
+              echo "CronJob schedule is valid."
           else
-            echo "CronJob schedule is valid."
+              echo "Invalid CronJob schedule format. Please use a valid cron format."
+              exit 1
           fi
 
       - name: Apply CronJob Schedule Change
